'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace BingMapsImageService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RequestBase", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(BingMapsImageService.MapUriRequest)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(BingMapsImageService.ImageryMetadataRequest))>  _
    Partial Public Class RequestBase
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CredentialsField As BingMapsImageService.Credentials
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CultureField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ExecutionOptionsField As BingMapsImageService.ExecutionOptions
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserProfileField As BingMapsImageService.UserProfile
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Credentials() As BingMapsImageService.Credentials
            Get
                Return Me.CredentialsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CredentialsField, value) <> true) Then
                    Me.CredentialsField = value
                    Me.RaisePropertyChanged("Credentials")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Culture() As String
            Get
                Return Me.CultureField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CultureField, value) <> true) Then
                    Me.CultureField = value
                    Me.RaisePropertyChanged("Culture")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ExecutionOptions() As BingMapsImageService.ExecutionOptions
            Get
                Return Me.ExecutionOptionsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ExecutionOptionsField, value) <> true) Then
                    Me.ExecutionOptionsField = value
                    Me.RaisePropertyChanged("ExecutionOptions")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserProfile() As BingMapsImageService.UserProfile
            Get
                Return Me.UserProfileField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserProfileField, value) <> true) Then
                    Me.UserProfileField = value
                    Me.RaisePropertyChanged("UserProfile")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Credentials", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Credentials
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ApplicationIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TokenField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ApplicationId() As String
            Get
                Return Me.ApplicationIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ApplicationIdField, value) <> true) Then
                    Me.ApplicationIdField = value
                    Me.RaisePropertyChanged("ApplicationId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Token() As String
            Get
                Return Me.TokenField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TokenField, value) <> true) Then
                    Me.TokenField = value
                    Me.RaisePropertyChanged("Token")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ExecutionOptions", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ExecutionOptions
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SuppressFaultsField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SuppressFaults() As Boolean
            Get
                Return Me.SuppressFaultsField
            End Get
            Set
                If (Me.SuppressFaultsField.Equals(value) <> true) Then
                    Me.SuppressFaultsField = value
                    Me.RaisePropertyChanged("SuppressFaults")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UserProfile", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UserProfile
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CurrentHeadingField As BingMapsImageService.Heading
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CurrentLocationField As BingMapsImageService.UserLocation
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DeviceTypeField As BingMapsImageService.DeviceType
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DistanceUnitField As BingMapsImageService.DistanceUnit
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IPAddressField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MapViewField As BingMapsImageService.ShapeBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ScreenSizeField As BingMapsImageService.SizeOfint
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CurrentHeading() As BingMapsImageService.Heading
            Get
                Return Me.CurrentHeadingField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CurrentHeadingField, value) <> true) Then
                    Me.CurrentHeadingField = value
                    Me.RaisePropertyChanged("CurrentHeading")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CurrentLocation() As BingMapsImageService.UserLocation
            Get
                Return Me.CurrentLocationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CurrentLocationField, value) <> true) Then
                    Me.CurrentLocationField = value
                    Me.RaisePropertyChanged("CurrentLocation")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DeviceType() As BingMapsImageService.DeviceType
            Get
                Return Me.DeviceTypeField
            End Get
            Set
                If (Me.DeviceTypeField.Equals(value) <> true) Then
                    Me.DeviceTypeField = value
                    Me.RaisePropertyChanged("DeviceType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DistanceUnit() As BingMapsImageService.DistanceUnit
            Get
                Return Me.DistanceUnitField
            End Get
            Set
                If (Me.DistanceUnitField.Equals(value) <> true) Then
                    Me.DistanceUnitField = value
                    Me.RaisePropertyChanged("DistanceUnit")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IPAddress() As String
            Get
                Return Me.IPAddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IPAddressField, value) <> true) Then
                    Me.IPAddressField = value
                    Me.RaisePropertyChanged("IPAddress")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MapView() As BingMapsImageService.ShapeBase
            Get
                Return Me.MapViewField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MapViewField, value) <> true) Then
                    Me.MapViewField = value
                    Me.RaisePropertyChanged("MapView")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ScreenSize() As BingMapsImageService.SizeOfint
            Get
                Return Me.ScreenSizeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ScreenSizeField, value) <> true) Then
                    Me.ScreenSizeField = value
                    Me.RaisePropertyChanged("ScreenSize")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MapUriRequest", [Namespace]:="http://dev.virtualearth.net/webservices/v1/imagery"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MapUriRequest
        Inherits BingMapsImageService.RequestBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CenterField As BingMapsImageService.Location
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MajorRoutesDestinationField As BingMapsImageService.Location
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OptionsField As BingMapsImageService.MapUriOptions
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PushpinsField() As BingMapsImageService.Pushpin
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Center() As BingMapsImageService.Location
            Get
                Return Me.CenterField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CenterField, value) <> true) Then
                    Me.CenterField = value
                    Me.RaisePropertyChanged("Center")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MajorRoutesDestination() As BingMapsImageService.Location
            Get
                Return Me.MajorRoutesDestinationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MajorRoutesDestinationField, value) <> true) Then
                    Me.MajorRoutesDestinationField = value
                    Me.RaisePropertyChanged("MajorRoutesDestination")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Options() As BingMapsImageService.MapUriOptions
            Get
                Return Me.OptionsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OptionsField, value) <> true) Then
                    Me.OptionsField = value
                    Me.RaisePropertyChanged("Options")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Pushpins() As BingMapsImageService.Pushpin()
            Get
                Return Me.PushpinsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PushpinsField, value) <> true) Then
                    Me.PushpinsField = value
                    Me.RaisePropertyChanged("Pushpins")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ImageryMetadataRequest", [Namespace]:="http://dev.virtualearth.net/webservices/v1/imagery"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ImageryMetadataRequest
        Inherits BingMapsImageService.RequestBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OptionsField As BingMapsImageService.ImageryMetadataOptions
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StyleField As BingMapsImageService.MapStyle
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Options() As BingMapsImageService.ImageryMetadataOptions
            Get
                Return Me.OptionsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OptionsField, value) <> true) Then
                    Me.OptionsField = value
                    Me.RaisePropertyChanged("Options")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Style() As BingMapsImageService.MapStyle
            Get
                Return Me.StyleField
            End Get
            Set
                If (Me.StyleField.Equals(value) <> true) Then
                    Me.StyleField = value
                    Me.RaisePropertyChanged("Style")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ImageryMetadataOptions", [Namespace]:="http://dev.virtualearth.net/webservices/v1/imagery"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ImageryMetadataOptions
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HeadingField As BingMapsImageService.Heading
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LocationField As BingMapsImageService.Location
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReturnImageryProvidersField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UriSchemeField As BingMapsImageService.UriScheme
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ZoomLevelField As System.Nullable(Of Integer)
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Heading() As BingMapsImageService.Heading
            Get
                Return Me.HeadingField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HeadingField, value) <> true) Then
                    Me.HeadingField = value
                    Me.RaisePropertyChanged("Heading")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Location() As BingMapsImageService.Location
            Get
                Return Me.LocationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LocationField, value) <> true) Then
                    Me.LocationField = value
                    Me.RaisePropertyChanged("Location")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ReturnImageryProviders() As Boolean
            Get
                Return Me.ReturnImageryProvidersField
            End Get
            Set
                If (Me.ReturnImageryProvidersField.Equals(value) <> true) Then
                    Me.ReturnImageryProvidersField = value
                    Me.RaisePropertyChanged("ReturnImageryProviders")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UriScheme() As BingMapsImageService.UriScheme
            Get
                Return Me.UriSchemeField
            End Get
            Set
                If (Me.UriSchemeField.Equals(value) <> true) Then
                    Me.UriSchemeField = value
                    Me.RaisePropertyChanged("UriScheme")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ZoomLevel() As System.Nullable(Of Integer)
            Get
                Return Me.ZoomLevelField
            End Get
            Set
                If (Me.ZoomLevelField.Equals(value) <> true) Then
                    Me.ZoomLevelField = value
                    Me.RaisePropertyChanged("ZoomLevel")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MapStyle", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Public Enum MapStyle As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Road = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Aerial = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        AerialWithLabels = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Birdseye = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        BirdseyeWithLabels = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Road_v0 = 5
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        AerialWithLabels_v0 = 6
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        BirdseyeWithLabels_v0 = 7
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Road_v1 = 8
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        AerialWithLabels_v1 = 9
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        BirdseyeWithLabels_v1 = 10
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Heading", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Heading
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrientationField As Double
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Orientation() As Double
            Get
                Return Me.OrientationField
            End Get
            Set
                If (Me.OrientationField.Equals(value) <> true) Then
                    Me.OrientationField = value
                    Me.RaisePropertyChanged("Orientation")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UserLocation", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UserLocation
        Inherits BingMapsImageService.Location
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ConfidenceField As BingMapsImageService.Confidence
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Confidence() As BingMapsImageService.Confidence
            Get
                Return Me.ConfidenceField
            End Get
            Set
                If (Me.ConfidenceField.Equals(value) <> true) Then
                    Me.ConfidenceField = value
                    Me.RaisePropertyChanged("Confidence")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ShapeBase", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(BingMapsImageService.SearchPoint)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(BingMapsImageService.Circle)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(BingMapsImageService.Rectangle)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(BingMapsImageService.Polygon))>  _
    Partial Public Class ShapeBase
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SizeOfint", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute()>  _
    Partial Public Class SizeOfint
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HeightField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private WidthField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Height() As Integer
            Get
                Return Me.HeightField
            End Get
            Set
                If (Me.HeightField.Equals(value) <> true) Then
                    Me.HeightField = value
                    Me.RaisePropertyChanged("Height")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Width() As Integer
            Get
                Return Me.WidthField
            End Get
            Set
                If (Me.WidthField.Equals(value) <> true) Then
                    Me.WidthField = value
                    Me.RaisePropertyChanged("Width")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DeviceType", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Public Enum DeviceType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Desktop = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Mobile = 1
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DistanceUnit", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Public Enum DistanceUnit As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Kilometer = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Mile = 1
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Location", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(BingMapsImageService.GeocodeLocation)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(BingMapsImageService.UserLocation))>  _
    Partial Public Class Location
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AltitudeField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LatitudeField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LongitudeField As Double
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Altitude() As Double
            Get
                Return Me.AltitudeField
            End Get
            Set
                If (Me.AltitudeField.Equals(value) <> true) Then
                    Me.AltitudeField = value
                    Me.RaisePropertyChanged("Altitude")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Latitude() As Double
            Get
                Return Me.LatitudeField
            End Get
            Set
                If (Me.LatitudeField.Equals(value) <> true) Then
                    Me.LatitudeField = value
                    Me.RaisePropertyChanged("Latitude")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Longitude() As Double
            Get
                Return Me.LongitudeField
            End Get
            Set
                If (Me.LongitudeField.Equals(value) <> true) Then
                    Me.LongitudeField = value
                    Me.RaisePropertyChanged("Longitude")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GeocodeLocation", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GeocodeLocation
        Inherits BingMapsImageService.Location
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CalculationMethodField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CalculationMethod() As String
            Get
                Return Me.CalculationMethodField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CalculationMethodField, value) <> true) Then
                    Me.CalculationMethodField = value
                    Me.RaisePropertyChanged("CalculationMethod")
                End If
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Confidence", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Public Enum Confidence As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        High = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Medium = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Low = 2
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SearchPoint", [Namespace]:="http://dev.virtualearth.net/webservices/v1/search"),  _
     System.SerializableAttribute()>  _
    Partial Public Class SearchPoint
        Inherits BingMapsImageService.ShapeBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PointField As BingMapsImageService.Location
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Point() As BingMapsImageService.Location
            Get
                Return Me.PointField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PointField, value) <> true) Then
                    Me.PointField = value
                    Me.RaisePropertyChanged("Point")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Circle", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Circle
        Inherits BingMapsImageService.ShapeBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CenterField As BingMapsImageService.Location
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DistanceUnitField As BingMapsImageService.DistanceUnit
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RadiusField As Double
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Center() As BingMapsImageService.Location
            Get
                Return Me.CenterField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CenterField, value) <> true) Then
                    Me.CenterField = value
                    Me.RaisePropertyChanged("Center")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DistanceUnit() As BingMapsImageService.DistanceUnit
            Get
                Return Me.DistanceUnitField
            End Get
            Set
                If (Me.DistanceUnitField.Equals(value) <> true) Then
                    Me.DistanceUnitField = value
                    Me.RaisePropertyChanged("DistanceUnit")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Radius() As Double
            Get
                Return Me.RadiusField
            End Get
            Set
                If (Me.RadiusField.Equals(value) <> true) Then
                    Me.RadiusField = value
                    Me.RaisePropertyChanged("Radius")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Rectangle", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Rectangle
        Inherits BingMapsImageService.ShapeBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NortheastField As BingMapsImageService.Location
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SouthwestField As BingMapsImageService.Location
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Northeast() As BingMapsImageService.Location
            Get
                Return Me.NortheastField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NortheastField, value) <> true) Then
                    Me.NortheastField = value
                    Me.RaisePropertyChanged("Northeast")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Southwest() As BingMapsImageService.Location
            Get
                Return Me.SouthwestField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SouthwestField, value) <> true) Then
                    Me.SouthwestField = value
                    Me.RaisePropertyChanged("Southwest")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Polygon", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Polygon
        Inherits BingMapsImageService.ShapeBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VerticesField() As BingMapsImageService.Location
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Vertices() As BingMapsImageService.Location()
            Get
                Return Me.VerticesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VerticesField, value) <> true) Then
                    Me.VerticesField = value
                    Me.RaisePropertyChanged("Vertices")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MapUriOptions", [Namespace]:="http://dev.virtualearth.net/webservices/v1/imagery"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MapUriOptions
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DisplayLayersField() As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ImageSizeField As BingMapsImageService.SizeOfint
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ImageTypeField As BingMapsImageService.ImageType
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PreventIconCollisionField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StyleField As BingMapsImageService.MapStyle
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UriSchemeField As BingMapsImageService.UriScheme
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ZoomLevelField As System.Nullable(Of Integer)
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DisplayLayers() As String()
            Get
                Return Me.DisplayLayersField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DisplayLayersField, value) <> true) Then
                    Me.DisplayLayersField = value
                    Me.RaisePropertyChanged("DisplayLayers")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ImageSize() As BingMapsImageService.SizeOfint
            Get
                Return Me.ImageSizeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ImageSizeField, value) <> true) Then
                    Me.ImageSizeField = value
                    Me.RaisePropertyChanged("ImageSize")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ImageType() As BingMapsImageService.ImageType
            Get
                Return Me.ImageTypeField
            End Get
            Set
                If (Me.ImageTypeField.Equals(value) <> true) Then
                    Me.ImageTypeField = value
                    Me.RaisePropertyChanged("ImageType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PreventIconCollision() As Boolean
            Get
                Return Me.PreventIconCollisionField
            End Get
            Set
                If (Me.PreventIconCollisionField.Equals(value) <> true) Then
                    Me.PreventIconCollisionField = value
                    Me.RaisePropertyChanged("PreventIconCollision")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Style() As BingMapsImageService.MapStyle
            Get
                Return Me.StyleField
            End Get
            Set
                If (Me.StyleField.Equals(value) <> true) Then
                    Me.StyleField = value
                    Me.RaisePropertyChanged("Style")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UriScheme() As BingMapsImageService.UriScheme
            Get
                Return Me.UriSchemeField
            End Get
            Set
                If (Me.UriSchemeField.Equals(value) <> true) Then
                    Me.UriSchemeField = value
                    Me.RaisePropertyChanged("UriScheme")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ZoomLevel() As System.Nullable(Of Integer)
            Get
                Return Me.ZoomLevelField
            End Get
            Set
                If (Me.ZoomLevelField.Equals(value) <> true) Then
                    Me.ZoomLevelField = value
                    Me.RaisePropertyChanged("ZoomLevel")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Pushpin", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Pushpin
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IconStyleField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LabelField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LocationField As BingMapsImageService.Location
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IconStyle() As String
            Get
                Return Me.IconStyleField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IconStyleField, value) <> true) Then
                    Me.IconStyleField = value
                    Me.RaisePropertyChanged("IconStyle")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Label() As String
            Get
                Return Me.LabelField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LabelField, value) <> true) Then
                    Me.LabelField = value
                    Me.RaisePropertyChanged("Label")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Location() As BingMapsImageService.Location
            Get
                Return Me.LocationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LocationField, value) <> true) Then
                    Me.LocationField = value
                    Me.RaisePropertyChanged("Location")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ImageType", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Public Enum ImageType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        [Default] = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Png = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Jpeg = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Gif = 3
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UriScheme", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Public Enum UriScheme As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Http = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Https = 1
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ResponseBase", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(BingMapsImageService.MapUriResponse)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(BingMapsImageService.ImageryMetadataResponse))>  _
    Partial Public Class ResponseBase
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BrandLogoUriField As System.Uri
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ResponseSummaryField As BingMapsImageService.ResponseSummary
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BrandLogoUri() As System.Uri
            Get
                Return Me.BrandLogoUriField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BrandLogoUriField, value) <> true) Then
                    Me.BrandLogoUriField = value
                    Me.RaisePropertyChanged("BrandLogoUri")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ResponseSummary() As BingMapsImageService.ResponseSummary
            Get
                Return Me.ResponseSummaryField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ResponseSummaryField, value) <> true) Then
                    Me.ResponseSummaryField = value
                    Me.RaisePropertyChanged("ResponseSummary")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ResponseSummary", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ResponseSummary
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AuthenticationResultCodeField As BingMapsImageService.AuthenticationResultCode
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CopyrightField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FaultReasonField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusCodeField As BingMapsImageService.ResponseStatusCode
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TraceIdField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AuthenticationResultCode() As BingMapsImageService.AuthenticationResultCode
            Get
                Return Me.AuthenticationResultCodeField
            End Get
            Set
                If (Me.AuthenticationResultCodeField.Equals(value) <> true) Then
                    Me.AuthenticationResultCodeField = value
                    Me.RaisePropertyChanged("AuthenticationResultCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Copyright() As String
            Get
                Return Me.CopyrightField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CopyrightField, value) <> true) Then
                    Me.CopyrightField = value
                    Me.RaisePropertyChanged("Copyright")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FaultReason() As String
            Get
                Return Me.FaultReasonField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FaultReasonField, value) <> true) Then
                    Me.FaultReasonField = value
                    Me.RaisePropertyChanged("FaultReason")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StatusCode() As BingMapsImageService.ResponseStatusCode
            Get
                Return Me.StatusCodeField
            End Get
            Set
                If (Me.StatusCodeField.Equals(value) <> true) Then
                    Me.StatusCodeField = value
                    Me.RaisePropertyChanged("StatusCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TraceId() As String
            Get
                Return Me.TraceIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TraceIdField, value) <> true) Then
                    Me.TraceIdField = value
                    Me.RaisePropertyChanged("TraceId")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MapUriResponse", [Namespace]:="http://dev.virtualearth.net/webservices/v1/imagery"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MapUriResponse
        Inherits BingMapsImageService.ResponseBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UriField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Uri() As String
            Get
                Return Me.UriField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UriField, value) <> true) Then
                    Me.UriField = value
                    Me.RaisePropertyChanged("Uri")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ImageryMetadataResponse", [Namespace]:="http://dev.virtualearth.net/webservices/v1/imagery"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ImageryMetadataResponse
        Inherits BingMapsImageService.ResponseBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ResultsField() As BingMapsImageService.ImageryMetadataResult
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Results() As BingMapsImageService.ImageryMetadataResult()
            Get
                Return Me.ResultsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ResultsField, value) <> true) Then
                    Me.ResultsField = value
                    Me.RaisePropertyChanged("Results")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ImageryMetadataResult", [Namespace]:="http://dev.virtualearth.net/webservices/v1/imagery"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(BingMapsImageService.ImageryMetadataBirdseyeResult))>  _
    Partial Public Class ImageryMetadataResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ImageSizeField As BingMapsImageService.SizeOfint
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ImageUriField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ImageUriSubdomainsField() As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ImageryProvidersField() As BingMapsImageService.ImageryProvider
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VintageField As BingMapsImageService.RangeOfdateTime
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ZoomRangeField As BingMapsImageService.RangeOfint
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ImageSize() As BingMapsImageService.SizeOfint
            Get
                Return Me.ImageSizeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ImageSizeField, value) <> true) Then
                    Me.ImageSizeField = value
                    Me.RaisePropertyChanged("ImageSize")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ImageUri() As String
            Get
                Return Me.ImageUriField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ImageUriField, value) <> true) Then
                    Me.ImageUriField = value
                    Me.RaisePropertyChanged("ImageUri")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ImageUriSubdomains() As String()
            Get
                Return Me.ImageUriSubdomainsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ImageUriSubdomainsField, value) <> true) Then
                    Me.ImageUriSubdomainsField = value
                    Me.RaisePropertyChanged("ImageUriSubdomains")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ImageryProviders() As BingMapsImageService.ImageryProvider()
            Get
                Return Me.ImageryProvidersField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ImageryProvidersField, value) <> true) Then
                    Me.ImageryProvidersField = value
                    Me.RaisePropertyChanged("ImageryProviders")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Vintage() As BingMapsImageService.RangeOfdateTime
            Get
                Return Me.VintageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VintageField, value) <> true) Then
                    Me.VintageField = value
                    Me.RaisePropertyChanged("Vintage")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ZoomRange() As BingMapsImageService.RangeOfint
            Get
                Return Me.ZoomRangeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ZoomRangeField, value) <> true) Then
                    Me.ZoomRangeField = value
                    Me.RaisePropertyChanged("ZoomRange")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AuthenticationResultCode", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Public Enum AuthenticationResultCode As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        None = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NoCredentials = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ValidCredentials = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        InvalidCredentials = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        CredentialsExpired = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NotAuthorized = 7
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ResponseStatusCode", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Public Enum ResponseStatusCode As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Success = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        BadRequest = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ServerError = 2
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RangeOfdateTime", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RangeOfdateTime
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FromField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ToField As Date
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property From() As Date
            Get
                Return Me.FromField
            End Get
            Set
                If (Me.FromField.Equals(value) <> true) Then
                    Me.FromField = value
                    Me.RaisePropertyChanged("From")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property [To]() As Date
            Get
                Return Me.ToField
            End Get
            Set
                If (Me.ToField.Equals(value) <> true) Then
                    Me.ToField = value
                    Me.RaisePropertyChanged("To")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RangeOfint", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RangeOfint
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FromField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ToField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property From() As Integer
            Get
                Return Me.FromField
            End Get
            Set
                If (Me.FromField.Equals(value) <> true) Then
                    Me.FromField = value
                    Me.RaisePropertyChanged("From")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property [To]() As Integer
            Get
                Return Me.ToField
            End Get
            Set
                If (Me.ToField.Equals(value) <> true) Then
                    Me.ToField = value
                    Me.RaisePropertyChanged("To")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ImageryMetadataBirdseyeResult", [Namespace]:="http://dev.virtualearth.net/webservices/v1/imagery"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ImageryMetadataBirdseyeResult
        Inherits BingMapsImageService.ImageryMetadataResult
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HeadingField As BingMapsImageService.Heading
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TilesXField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TilesYField As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Heading() As BingMapsImageService.Heading
            Get
                Return Me.HeadingField
            End Get
            Set
                If (Object.ReferenceEquals(Me.HeadingField, value) <> true) Then
                    Me.HeadingField = value
                    Me.RaisePropertyChanged("Heading")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TilesX() As Integer
            Get
                Return Me.TilesXField
            End Get
            Set
                If (Me.TilesXField.Equals(value) <> true) Then
                    Me.TilesXField = value
                    Me.RaisePropertyChanged("TilesX")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TilesY() As Integer
            Get
                Return Me.TilesYField
            End Get
            Set
                If (Me.TilesYField.Equals(value) <> true) Then
                    Me.TilesYField = value
                    Me.RaisePropertyChanged("TilesY")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ImageryProvider", [Namespace]:="http://dev.virtualearth.net/webservices/v1/imagery"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ImageryProvider
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AttributionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CoverageAreasField() As BingMapsImageService.CoverageArea
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Attribution() As String
            Get
                Return Me.AttributionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AttributionField, value) <> true) Then
                    Me.AttributionField = value
                    Me.RaisePropertyChanged("Attribution")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CoverageAreas() As BingMapsImageService.CoverageArea()
            Get
                Return Me.CoverageAreasField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CoverageAreasField, value) <> true) Then
                    Me.CoverageAreasField = value
                    Me.RaisePropertyChanged("CoverageAreas")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CoverageArea", [Namespace]:="http://dev.virtualearth.net/webservices/v1/imagery"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CoverageArea
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BoundingRectangleField As BingMapsImageService.Rectangle
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ZoomRangeField As BingMapsImageService.RangeOfint
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BoundingRectangle() As BingMapsImageService.Rectangle
            Get
                Return Me.BoundingRectangleField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BoundingRectangleField, value) <> true) Then
                    Me.BoundingRectangleField = value
                    Me.RaisePropertyChanged("BoundingRectangle")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ZoomRange() As BingMapsImageService.RangeOfint
            Get
                Return Me.ZoomRangeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ZoomRangeField, value) <> true) Then
                    Me.ZoomRangeField = value
                    Me.RaisePropertyChanged("ZoomRange")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/imagery/contracts", ConfigurationName:="BingMapsImageService.IImageryService")>  _
    Public Interface IImageryService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://dev.virtualearth.net/webservices/v1/imagery/contracts/IImageryService/GetI"& _ 
            "mageryMetadata", ReplyAction:="http://dev.virtualearth.net/webservices/v1/imagery/contracts/IImageryService/GetI"& _ 
            "mageryMetadataResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(BingMapsImageService.ResponseSummary), Action:="http://dev.virtualearth.net/webservices/v1/imagery/contracts/IImageryService/GetI"& _ 
            "mageryMetadataResponseSummaryFault", Name:="ResponseSummary", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
        Function GetImageryMetadata(ByVal request As BingMapsImageService.ImageryMetadataRequest) As BingMapsImageService.ImageryMetadataResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://dev.virtualearth.net/webservices/v1/imagery/contracts/IImageryService/GetI"& _ 
            "mageryMetadata", ReplyAction:="http://dev.virtualearth.net/webservices/v1/imagery/contracts/IImageryService/GetI"& _ 
            "mageryMetadataResponse")>  _
        Function GetImageryMetadataAsync(ByVal request As BingMapsImageService.ImageryMetadataRequest) As System.Threading.Tasks.Task(Of BingMapsImageService.ImageryMetadataResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://dev.virtualearth.net/webservices/v1/imagery/contracts/IImageryService/GetM"& _ 
            "apUri", ReplyAction:="http://dev.virtualearth.net/webservices/v1/imagery/contracts/IImageryService/GetM"& _ 
            "apUriResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(BingMapsImageService.ResponseSummary), Action:="http://dev.virtualearth.net/webservices/v1/imagery/contracts/IImageryService/GetM"& _ 
            "apUriResponseSummaryFault", Name:="ResponseSummary", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
        Function GetMapUri(ByVal request As BingMapsImageService.MapUriRequest) As BingMapsImageService.MapUriResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://dev.virtualearth.net/webservices/v1/imagery/contracts/IImageryService/GetM"& _ 
            "apUri", ReplyAction:="http://dev.virtualearth.net/webservices/v1/imagery/contracts/IImageryService/GetM"& _ 
            "apUriResponse")>  _
        Function GetMapUriAsync(ByVal request As BingMapsImageService.MapUriRequest) As System.Threading.Tasks.Task(Of BingMapsImageService.MapUriResponse)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IImageryServiceChannel
        Inherits BingMapsImageService.IImageryService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ImageryServiceClient
        Inherits System.ServiceModel.ClientBase(Of BingMapsImageService.IImageryService)
        Implements BingMapsImageService.IImageryService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetImageryMetadata(ByVal request As BingMapsImageService.ImageryMetadataRequest) As BingMapsImageService.ImageryMetadataResponse Implements BingMapsImageService.IImageryService.GetImageryMetadata
            Return MyBase.Channel.GetImageryMetadata(request)
        End Function
        
        Public Function GetImageryMetadataAsync(ByVal request As BingMapsImageService.ImageryMetadataRequest) As System.Threading.Tasks.Task(Of BingMapsImageService.ImageryMetadataResponse) Implements BingMapsImageService.IImageryService.GetImageryMetadataAsync
            Return MyBase.Channel.GetImageryMetadataAsync(request)
        End Function
        
        Public Function GetMapUri(ByVal request As BingMapsImageService.MapUriRequest) As BingMapsImageService.MapUriResponse Implements BingMapsImageService.IImageryService.GetMapUri
            Return MyBase.Channel.GetMapUri(request)
        End Function
        
        Public Function GetMapUriAsync(ByVal request As BingMapsImageService.MapUriRequest) As System.Threading.Tasks.Task(Of BingMapsImageService.MapUriResponse) Implements BingMapsImageService.IImageryService.GetMapUriAsync
            Return MyBase.Channel.GetMapUriAsync(request)
        End Function
    End Class
End Namespace
